import type { PluginInfo } from "./types";

type KnownPlugin = Omit<PluginInfo, "slug">;

/** Popular WordPress plugins by wp-content/plugins/[slug] directory name. */
export const KNOWN_PLUGINS: Record<string, KnownPlugin> = {
  elementor: { name: "Elementor Website Builder", wpOrgUrl: "https://wordpress.org/plugins/elementor/", ourArticleUrl: "/elementor-vs-divi" },
  "wordpress-seo": { name: "Yoast SEO", wpOrgUrl: "https://wordpress.org/plugins/wordpress-seo/", ourArticleUrl: "/yoast-vs-rank-math" },
  "contact-form-7": { name: "Contact Form 7", wpOrgUrl: "https://wordpress.org/plugins/contact-form-7/", ourArticleUrl: "/best-contact-form-plugins" },
  "classic-editor": { name: "Classic Editor", wpOrgUrl: "https://wordpress.org/plugins/classic-editor/", ourArticleUrl: "/classic-editor-review" },
  "litespeed-cache": { name: "LiteSpeed Cache", wpOrgUrl: "https://wordpress.org/plugins/litespeed-cache/", ourArticleUrl: "/best-caching-plugins" },
  woocommerce: { name: "WooCommerce", wpOrgUrl: "https://wordpress.org/plugins/woocommerce/", ourArticleUrl: "/create-online-store-wordpress" },
  akismet: { name: "Akismet Anti-spam: Spam Protection", wpOrgUrl: "https://wordpress.org/plugins/akismet/", ourArticleUrl: "/essential-wordpress-plugins-beginners" },
  "wpforms-lite": { name: "WPForms", wpOrgUrl: "https://wordpress.org/plugins/wpforms-lite/", ourArticleUrl: "/best-contact-form-plugins" },
  "google-site-kit": { name: "Site Kit by Google", wpOrgUrl: "https://wordpress.org/plugins/google-site-kit/", ourArticleUrl: "/install-google-analytics-wordpress" },
  "all-in-one-wp-migration": { name: "All-in-One WP Migration and Backup", wpOrgUrl: "https://wordpress.org/plugins/all-in-one-wp-migration/", ourArticleUrl: "/all-in-one-wp-migration-review" },
  wordfence: { name: "Wordfence Security", wpOrgUrl: "https://wordpress.org/plugins/wordfence/", ourArticleUrl: "/best-security-plugins" },
  "wp-mail-smtp": { name: "WP Mail SMTP by WPForms", wpOrgUrl: "https://wordpress.org/plugins/wp-mail-smtp/", ourArticleUrl: "/wordpress-email-setup" },
  "duplicate-post": { name: "Yoast Duplicate Post", wpOrgUrl: "https://wordpress.org/plugins/duplicate-post/", ourArticleUrl: "/duplicate-post-review" },
  "really-simple-ssl": { name: "Really Simple Security", wpOrgUrl: "https://wordpress.org/plugins/really-simple-ssl/", ourArticleUrl: "/setup-ssl-wordpress" },
  "seo-by-rank-math": { name: "Rank Math SEO", wpOrgUrl: "https://wordpress.org/plugins/seo-by-rank-math/", ourArticleUrl: "/yoast-vs-rank-math" },
  "duplicate-page": { name: "Duplicate Page", wpOrgUrl: "https://wordpress.org/plugins/duplicate-page/", ourArticleUrl: "/duplicate-page-review" },
  updraftplus: { name: "UpdraftPlus: WP Backup & Migration Plugin", wpOrgUrl: "https://wordpress.org/plugins/updraftplus/", ourArticleUrl: "/wordpress-backup-guide" },
  jetpack: { name: "Jetpack", wpOrgUrl: "https://wordpress.org/plugins/jetpack/", ourArticleUrl: "/best-wordpress-plugins" },
  "all-in-one-seo-pack": { name: "All in One SEO", wpOrgUrl: "https://wordpress.org/plugins/all-in-one-seo-pack/", ourArticleUrl: "/best-wordpress-seo-plugins" },
  hostinger: { name: "Hostinger Tools", wpOrgUrl: "https://wordpress.org/plugins/hostinger/", ourArticleUrl: "/hostinger-review" },
  "insert-headers-and-footers": { name: "WPCode", wpOrgUrl: "https://wordpress.org/plugins/insert-headers-and-footers/", ourArticleUrl: "/wpcode-review" },
  "wordpress-importer": { name: "WordPress Importer", wpOrgUrl: "https://wordpress.org/plugins/wordpress-importer/", ourArticleUrl: "/wordpress-importer-review" },
  redirection: { name: "Redirection", wpOrgUrl: "https://wordpress.org/plugins/redirection/", ourArticleUrl: "/redirection-plugin-review" },
  "google-analytics-for-wordpress": { name: "MonsterInsights", wpOrgUrl: "https://wordpress.org/plugins/google-analytics-for-wordpress/", ourArticleUrl: "/install-google-analytics-wordpress" },
  "classic-widgets": { name: "Classic Widgets", wpOrgUrl: "https://wordpress.org/plugins/classic-widgets/", ourArticleUrl: "/classic-widgets-review" },
  "header-footer-elementor": { name: "Ultimate Addons for Elementor", wpOrgUrl: "https://wordpress.org/plugins/header-footer-elementor/", ourArticleUrl: "/ultimate-addons-elementor-review" },
  "advanced-custom-fields": { name: "Advanced Custom Fields", wpOrgUrl: "https://wordpress.org/plugins/advanced-custom-fields/", ourArticleUrl: "/acf-review" },
  "wps-hide-login": { name: "WPS Hide Login", wpOrgUrl: "https://wordpress.org/plugins/wps-hide-login/", ourArticleUrl: "/wordpress-login-security" },
  "essential-addons-for-elementor-lite": { name: "Essential Addons for Elementor", wpOrgUrl: "https://wordpress.org/plugins/essential-addons-for-elementor-lite/", ourArticleUrl: "/essential-addons-elementor-review" },
  "tinymce-advanced": { name: "Advanced Editor Tools", wpOrgUrl: "https://wordpress.org/plugins/tinymce-advanced/", ourArticleUrl: "/advanced-editor-tools-review" },
  "limit-login-attempts-reloaded": { name: "Limit Login Attempts Reloaded", wpOrgUrl: "https://wordpress.org/plugins/limit-login-attempts-reloaded/", ourArticleUrl: "/wordpress-login-security" },
  "astra-sites": { name: "Starter Templates", wpOrgUrl: "https://wordpress.org/plugins/astra-sites/", ourArticleUrl: "/astra-theme-review" },
  "elementskit-lite": { name: "ElementsKit Elementor Addons", wpOrgUrl: "https://wordpress.org/plugins/elementskit-lite/", ourArticleUrl: "/elementskit-review" },
  "mailchimp-for-wp": { name: "MC4WP: Mailchimp for WordPress", wpOrgUrl: "https://wordpress.org/plugins/mailchimp-for-wp/", ourArticleUrl: "/best-email-marketing-plugins" },
  "loco-translate": { name: "Loco Translate", wpOrgUrl: "https://wordpress.org/plugins/loco-translate/", ourArticleUrl: "/loco-translate-review" },
  "disable-comments": { name: "Disable Comments", wpOrgUrl: "https://wordpress.org/plugins/disable-comments/", ourArticleUrl: "/disable-comments-review" },
  "wp-super-cache": { name: "WP Super Cache", wpOrgUrl: "https://wordpress.org/plugins/wp-super-cache/", ourArticleUrl: "/best-caching-plugins" },
  duplicator: { name: "Duplicator", wpOrgUrl: "https://wordpress.org/plugins/duplicator/", ourArticleUrl: "/migrate-wordpress-to-new-host" },
  "cookie-law-info": { name: "CookieYes", wpOrgUrl: "https://wordpress.org/plugins/cookie-law-info/", ourArticleUrl: "/cookieyes-review" },
  loginizer: { name: "Loginizer", wpOrgUrl: "https://wordpress.org/plugins/loginizer/", ourArticleUrl: "/wordpress-login-security" },
  "better-search-replace": { name: "Better Search Replace", wpOrgUrl: "https://wordpress.org/plugins/better-search-replace/", ourArticleUrl: "/better-search-replace-review" },
  "wp-file-manager": { name: "File Manager", wpOrgUrl: "https://wordpress.org/plugins/wp-file-manager/", ourArticleUrl: "/file-manager-review" },
  "code-snippets": { name: "Code Snippets", wpOrgUrl: "https://wordpress.org/plugins/code-snippets/", ourArticleUrl: "/best-code-snippet-plugins" },
  "wp-fastest-cache": { name: "WP Fastest Cache", wpOrgUrl: "https://wordpress.org/plugins/wp-fastest-cache/", ourArticleUrl: "/best-caching-plugins" },
  "complianz-gdpr": { name: "Complianz", wpOrgUrl: "https://wordpress.org/plugins/complianz-gdpr/", ourArticleUrl: null },
  "svg-support": { name: "SVG Support", wpOrgUrl: "https://wordpress.org/plugins/svg-support/", ourArticleUrl: null },
  "sg-cachepress": { name: "Speed Optimizer", wpOrgUrl: "https://wordpress.org/plugins/sg-cachepress/", ourArticleUrl: null },
  "custom-post-type-ui": { name: "Custom Post Type UI", wpOrgUrl: "https://wordpress.org/plugins/custom-post-type-ui/", ourArticleUrl: null },
  "one-click-demo-import": { name: "One Click Demo Import", wpOrgUrl: "https://wordpress.org/plugins/one-click-demo-import/", ourArticleUrl: null },
  optinmonster: { name: "Popup Builder & Popup Maker for WordPress", wpOrgUrl: "https://wordpress.org/plugins/optinmonster/", ourArticleUrl: null },
  "wp-optimize": { name: "WP-Optimize", wpOrgUrl: "https://wordpress.org/plugins/wp-optimize/", ourArticleUrl: "/wordpress-database-optimization" },
  "google-sitemap-generator": { name: "XML Sitemap Generator for Google", wpOrgUrl: "https://wordpress.org/plugins/google-sitemap-generator/", ourArticleUrl: null },
  worker: { name: "ManageWP Worker", wpOrgUrl: "https://wordpress.org/plugins/worker/", ourArticleUrl: null },
  "ultimate-addons-for-gutenberg": { name: "Spectra Gutenberg Blocks", wpOrgUrl: "https://wordpress.org/plugins/ultimate-addons-for-gutenberg/", ourArticleUrl: null },
  maintenance: { name: "Maintenance", wpOrgUrl: "https://wordpress.org/plugins/maintenance/", ourArticleUrl: null },
  "image-optimization": { name: "Image Optimizer", wpOrgUrl: "https://wordpress.org/plugins/image-optimization/", ourArticleUrl: null },
  "safe-svg": { name: "Safe SVG", wpOrgUrl: "https://wordpress.org/plugins/safe-svg/", ourArticleUrl: null },
  "instagram-feed": { name: "Smash Balloon Social Photo Feed", wpOrgUrl: "https://wordpress.org/plugins/instagram-feed/", ourArticleUrl: null },
  "wp-smushit": { name: "Smush Image Optimization", wpOrgUrl: "https://wordpress.org/plugins/wp-smushit/", ourArticleUrl: "/best-image-optimization-plugins" },
  "regenerate-thumbnails": { name: "Regenerate Thumbnails", wpOrgUrl: "https://wordpress.org/plugins/regenerate-thumbnails/", ourArticleUrl: null },
  "ewww-image-optimizer": { name: "EWWW Image Optimizer", wpOrgUrl: "https://wordpress.org/plugins/ewww-image-optimizer/", ourArticleUrl: "/best-image-optimization-plugins" },
  "all-in-one-wp-security-and-firewall": { name: "All-In-One Security", wpOrgUrl: "https://wordpress.org/plugins/all-in-one-wp-security-and-firewall/", ourArticleUrl: "/best-security-plugins" },
  "sg-security": { name: "Security Optimizer", wpOrgUrl: "https://wordpress.org/plugins/sg-security/", ourArticleUrl: null },
  "wp-multibyte-patch": { name: "WP Multibyte Patch", wpOrgUrl: "https://wordpress.org/plugins/wp-multibyte-patch/", ourArticleUrl: null },
  "redux-framework": { name: "Redux Framework", wpOrgUrl: "https://wordpress.org/plugins/redux-framework/", ourArticleUrl: null },
  imagify: { name: "Imagify Image Optimization", wpOrgUrl: "https://wordpress.org/plugins/imagify/", ourArticleUrl: "/best-image-optimization-plugins" },
  "hostinger-reach": { name: "Hostinger Reach", wpOrgUrl: "https://wordpress.org/plugins/hostinger-reach/", ourArticleUrl: null },
  "cookie-notice": { name: "Cookie Notice & Compliance for GDPR / CCPA", wpOrgUrl: "https://wordpress.org/plugins/cookie-notice/", ourArticleUrl: null },
  "w3-total-cache": { name: "W3 Total Cache", wpOrgUrl: "https://wordpress.org/plugins/w3-total-cache/", ourArticleUrl: "/best-caching-plugins" },
  autoptimize: { name: "Autoptimize", wpOrgUrl: "https://wordpress.org/plugins/autoptimize/", ourArticleUrl: null },
  "google-listings-and-ads": { name: "Google for WooCommerce", wpOrgUrl: "https://wordpress.org/plugins/google-listings-and-ads/", ourArticleUrl: null },
  "woocommerce-payments": { name: "WooPayments: Integrated WooCommerce Payments", wpOrgUrl: "https://wordpress.org/plugins/woocommerce-payments/", ourArticleUrl: null },
  gtranslate: { name: "Translate WordPress with GTranslate", wpOrgUrl: "https://wordpress.org/plugins/gtranslate/", ourArticleUrl: null },
  "wpvivid-backuprestore": { name: "WPvivid", wpOrgUrl: "https://wordpress.org/plugins/wpvivid-backuprestore/", ourArticleUrl: null },
  "wp-reviews-plugin-for-google": { name: "Widgets for Google Reviews", wpOrgUrl: "https://wordpress.org/plugins/wp-reviews-plugin-for-google/", ourArticleUrl: null },
  "smart-slider-3": { name: "Smart Slider 3", wpOrgUrl: "https://wordpress.org/plugins/smart-slider-3/", ourArticleUrl: null },
  "breadcrumb-navxt": { name: "Breadcrumb NavXT", wpOrgUrl: "https://wordpress.org/plugins/breadcrumb-navxt/", ourArticleUrl: null },
  polylang: { name: "Polylang", wpOrgUrl: "https://wordpress.org/plugins/polylang/", ourArticleUrl: null },
  "woocommerce-paypal-payments": { name: "WooCommerce PayPal Payments", wpOrgUrl: "https://wordpress.org/plugins/woocommerce-paypal-payments/", ourArticleUrl: null },
  flamingo: { name: "Flamingo", wpOrgUrl: "https://wordpress.org/plugins/flamingo/", ourArticleUrl: null },
  "better-wp-security": { name: "Solid Security", wpOrgUrl: "https://wordpress.org/plugins/better-wp-security/", ourArticleUrl: "/best-security-plugins" },
  "duracelltomi-google-tag-manager": { name: "GTM4WP", wpOrgUrl: "https://wordpress.org/plugins/duracelltomi-google-tag-manager/", ourArticleUrl: null },
  "antispam-bee": { name: "Antispam Bee", wpOrgUrl: "https://wordpress.org/plugins/antispam-bee/", ourArticleUrl: null },
  "woocommerce-gateway-stripe": { name: "WooCommerce Stripe Payment Gateway", wpOrgUrl: "https://wordpress.org/plugins/woocommerce-gateway-stripe/", ourArticleUrl: null },
  "coming-soon": { name: "Website Builder by SeedProd", wpOrgUrl: "https://wordpress.org/plugins/coming-soon/", ourArticleUrl: null },
  "premium-addons-for-elementor": { name: "Premium Addons for Elementor", wpOrgUrl: "https://wordpress.org/plugins/premium-addons-for-elementor/", ourArticleUrl: null },
  "creame-whatsapp-me": { name: "Joinchat", wpOrgUrl: "https://wordpress.org/plugins/creame-whatsapp-me/", ourArticleUrl: null },
  "mainwp-child": { name: "MainWP Child", wpOrgUrl: "https://wordpress.org/plugins/mainwp-child/", ourArticleUrl: null },
  "user-role-editor": { name: "User Role Editor", wpOrgUrl: "https://wordpress.org/plugins/user-role-editor/", ourArticleUrl: null },
  "popup-maker": { name: "Popup Maker", wpOrgUrl: "https://wordpress.org/plugins/popup-maker/", ourArticleUrl: null },
  "the-events-calendar": { name: "The Events Calendar", wpOrgUrl: "https://wordpress.org/plugins/the-events-calendar/", ourArticleUrl: null },
  "click-to-chat-for-whatsapp": { name: "Click to Chat", wpOrgUrl: "https://wordpress.org/plugins/click-to-chat-for-whatsapp/", ourArticleUrl: null },
  tablepress: { name: "TablePress", wpOrgUrl: "https://wordpress.org/plugins/tablepress/", ourArticleUrl: null },
  "custom-css-js": { name: "Simple Custom CSS and JS", wpOrgUrl: "https://wordpress.org/plugins/custom-css-js/", ourArticleUrl: null },
  backuply: { name: "Backuply", wpOrgUrl: "https://wordpress.org/plugins/backuply/", ourArticleUrl: null },
  fluentform: { name: "Fluent Forms", wpOrgUrl: "https://wordpress.org/plugins/fluentform/", ourArticleUrl: null },
  "royal-elementor-addons": { name: "Royal Addons for Elementor", wpOrgUrl: "https://wordpress.org/plugins/royal-elementor-addons/", ourArticleUrl: null },
  "sucuri-scanner": { name: "Sucuri Security", wpOrgUrl: "https://wordpress.org/plugins/sucuri-scanner/", ourArticleUrl: "/best-wordpress-firewall-plugins" },
  "hello-dolly": { name: "Hello Dolly", wpOrgUrl: "https://wordpress.org/plugins/hello-dolly/", ourArticleUrl: null },
  "under-construction-page": { name: "Under Construction", wpOrgUrl: "https://wordpress.org/plugins/under-construction-page/", ourArticleUrl: null },
  gravityforms: { name: "Gravity Forms", wpOrgUrl: null, ourArticleUrl: "/best-contact-form-plugins" },
  "js_composer": { name: "WPBakery Page Builder", wpOrgUrl: null, ourArticleUrl: null },
  revslider: { name: "Slider Revolution", wpOrgUrl: null, ourArticleUrl: null },
};

/** HTML patterns that indicate a specific plugin is active. */
export const PLUGIN_SIGNATURES: Array<{ pattern: RegExp; slug: string }> = [
  { pattern: /wpcf7/i, slug: "contact-form-7" },
  { pattern: /elementor/i, slug: "elementor" },
  { pattern: /woocommerce/i, slug: "woocommerce" },
  { pattern: /yoast-schema/i, slug: "wordpress-seo" },
  { pattern: /yoast-seo/i, slug: "wordpress-seo" },
  { pattern: /rank-math/i, slug: "seo-by-rank-math" },
  { pattern: /jetpack/i, slug: "jetpack" },
  { pattern: /wp-rocket/i, slug: "wp-rocket" },
  { pattern: /wpforms/i, slug: "wpforms-lite" },
  { pattern: /monsterinsights/i, slug: "google-analytics-for-wordpress" },
  { pattern: /gravityforms/i, slug: "gravityforms" },
];
