import type { ThemeInfo } from "./types";

type KnownTheme = Omit<ThemeInfo, "slug">;

/** Popular WordPress themes by wp-content/themes/[slug] directory name. */
export const KNOWN_THEMES: Record<string, KnownTheme> = {
  "Avada": { name: "Avada", isFree: false, wpOrgUrl: null, officialUrl: "https://avada.com/", ourReviewUrl: null },
  "Divi": { name: "Divi", isFree: false, wpOrgUrl: null, officialUrl: "https://www.elegantthemes.com/gallery/divi/", ourReviewUrl: "/elementor-vs-divi" },
  astra: { name: "Astra", isFree: true, wpOrgUrl: "https://wordpress.org/themes/astra/", officialUrl: "https://wpastra.com/", ourReviewUrl: "/astra-theme-review" },
  beTheme: { name: "BeTheme", isFree: false, wpOrgUrl: null, officialUrl: "https://betheme.me/", ourReviewUrl: null },
  blocksy: { name: "Blocksy", isFree: true, wpOrgUrl: "https://wordpress.org/themes/blocksy/", officialUrl: "https://creativethemes.com/blocksy/", ourReviewUrl: null },
  bridge: { name: "Bridge", isFree: false, wpOrgUrl: null, officialUrl: "https://qodeinteractive.com/wordpress-theme/bridge-creative-multi-purpose-wordpress-theme/", ourReviewUrl: null },
  "colibri-wp": { name: "Colibri WP", isFree: true, wpOrgUrl: "https://wordpress.org/themes/colibri-wp/", officialUrl: null, ourReviewUrl: null },
  enfold: { name: "Enfold", isFree: false, wpOrgUrl: null, officialUrl: "https://kriesi.at/themes/enfold/", ourReviewUrl: null },
  extendable: { name: "Extendable", isFree: true, wpOrgUrl: "https://wordpress.org/themes/extendable/", officialUrl: null, ourReviewUrl: null },
  flatsome: { name: "Flatsome", isFree: false, wpOrgUrl: null, officialUrl: null, ourReviewUrl: null },
  generatepress: { name: "GeneratePress", isFree: true, wpOrgUrl: "https://wordpress.org/themes/generatepress/", officialUrl: "https://generatepress.com/", ourReviewUrl: "/generatepress-vs-astra" },
  go: { name: "Go", isFree: true, wpOrgUrl: "https://wordpress.org/themes/go/", officialUrl: null, ourReviewUrl: null },
  "hello-biz": { name: "Hello Biz", isFree: true, wpOrgUrl: "https://wordpress.org/themes/hello-biz/", officialUrl: null, ourReviewUrl: null },
  "hello-elementor": { name: "Hello Elementor", isFree: true, wpOrgUrl: "https://wordpress.org/themes/hello-elementor/", officialUrl: "https://elementor.com/", ourReviewUrl: "/elementor-vs-divi" },
  hestia: { name: "Hestia", isFree: true, wpOrgUrl: "https://wordpress.org/themes/hestia/", officialUrl: "https://themeisle.com/themes/hestia/", ourReviewUrl: null },
  inspiro: { name: "Inspiro", isFree: true, wpOrgUrl: "https://wordpress.org/themes/inspiro/", officialUrl: null, ourReviewUrl: null },
  jupiter: { name: "Jupiter", isFree: false, wpOrgUrl: null, officialUrl: "https://themes.artbees.net/jupiter/", ourReviewUrl: null },
  kadence: { name: "Kadence", isFree: true, wpOrgUrl: "https://wordpress.org/themes/kadence/", officialUrl: "https://www.kadencewp.com/", ourReviewUrl: "/best-free-wordpress-themes" },
  kubio: { name: "Kubio", isFree: true, wpOrgUrl: "https://wordpress.org/themes/kubio/", officialUrl: "https://kubiobuilder.com/", ourReviewUrl: null },
  lightning: { name: "Lightning", isFree: true, wpOrgUrl: "https://wordpress.org/themes/lightning/", officialUrl: null, ourReviewUrl: null },
  neve: { name: "Neve", isFree: true, wpOrgUrl: "https://wordpress.org/themes/neve/", officialUrl: "https://themeisle.com/themes/neve/", ourReviewUrl: null },
  oceanwp: { name: "OceanWP", isFree: true, wpOrgUrl: "https://wordpress.org/themes/oceanwp/", officialUrl: "https://oceanwp.org/", ourReviewUrl: "/best-free-wordpress-themes" },
  onepress: { name: "OnePress", isFree: true, wpOrgUrl: "https://wordpress.org/themes/onepress/", officialUrl: null, ourReviewUrl: null },
  popularfx: { name: "PopularFX", isFree: true, wpOrgUrl: "https://wordpress.org/themes/popularfx/", officialUrl: null, ourReviewUrl: null },
  "royal-elementor-kit": { name: "Royal Elementor Kit", isFree: true, wpOrgUrl: "https://wordpress.org/themes/royal-elementor-kit/", officialUrl: null, ourReviewUrl: null },
  salient: { name: "Salient", isFree: false, wpOrgUrl: null, officialUrl: "https://themenectar.com/salient/", ourReviewUrl: null },
  storefront: { name: "Storefront", isFree: true, wpOrgUrl: "https://wordpress.org/themes/storefront/", officialUrl: "https://woocommerce.com/storefront/", ourReviewUrl: null },
  sydney: { name: "Sydney", isFree: true, wpOrgUrl: "https://wordpress.org/themes/sydney/", officialUrl: null, ourReviewUrl: null },
  the7: { name: "The7", isFree: false, wpOrgUrl: null, officialUrl: "https://the7.io/", ourReviewUrl: null },
  twentyfifteen: { name: "Twenty Fifteen", isFree: true, wpOrgUrl: "https://wordpress.org/themes/twentyfifteen/", officialUrl: null, ourReviewUrl: null },
  twentynineteen: { name: "Twenty Nineteen", isFree: true, wpOrgUrl: "https://wordpress.org/themes/twentynineteen/", officialUrl: null, ourReviewUrl: null },
  twentyseventeen: { name: "Twenty Seventeen", isFree: true, wpOrgUrl: "https://wordpress.org/themes/twentyseventeen/", officialUrl: null, ourReviewUrl: null },
  twentysixteen: { name: "Twenty Sixteen", isFree: true, wpOrgUrl: "https://wordpress.org/themes/twentysixteen/", officialUrl: null, ourReviewUrl: null },
  twentytwenty: { name: "Twenty Twenty", isFree: true, wpOrgUrl: "https://wordpress.org/themes/twentytwenty/", officialUrl: null, ourReviewUrl: null },
  twentytwentyfive: { name: "Twenty Twenty-Five", isFree: true, wpOrgUrl: "https://wordpress.org/themes/twentytwentyfive/", officialUrl: null, ourReviewUrl: null },
  twentytwentyfour: { name: "Twenty Twenty-Four", isFree: true, wpOrgUrl: "https://wordpress.org/themes/twentytwentyfour/", officialUrl: null, ourReviewUrl: null },
  twentytwentyone: { name: "Twenty Twenty-One", isFree: true, wpOrgUrl: "https://wordpress.org/themes/twentytwentyone/", officialUrl: null, ourReviewUrl: null },
  twentytwentythree: { name: "Twenty Twenty-Three", isFree: true, wpOrgUrl: "https://wordpress.org/themes/twentytwentythree/", officialUrl: null, ourReviewUrl: null },
  twentytwentytwo: { name: "Twenty Twenty-Two", isFree: true, wpOrgUrl: "https://wordpress.org/themes/twentytwentytwo/", officialUrl: null, ourReviewUrl: null },
  uncode: { name: "Uncode", isFree: false, wpOrgUrl: null, officialUrl: "https://undsgn.com/uncode/", ourReviewUrl: null },
  woodmart: { name: "WoodMart", isFree: false, wpOrgUrl: null, officialUrl: "https://woodmart.xtemos.com/", ourReviewUrl: null },
  woostify: { name: "Woostify", isFree: true, wpOrgUrl: "https://wordpress.org/themes/woostify/", officialUrl: "https://woostify.com/", ourReviewUrl: null },
};
